### ISSUE TITLE
I don't want to host the following images.

### ISSUE THREAD

**Issue by fideloper** [shipping-docker/php-app#1]
![twitter-banner](https://cloud.githubusercontent.com/assets/467411/18037588/0c4bd070-6d4e-11e6-8e86-12b6c8c5583d.png)
![twitter-square](https://cloud.githubusercontent.com/assets/467411/18037589/0e9c7118-6d4e-11e6-80ff-c650cbeb5a33.png)
![twitter](https://cloud.githubusercontent.com/assets/467411/18037593/12321512-6d4e-11e6-8514-e8454f4fd286.jpg)

**Comment by fideloper** [comment]
![image](https://cloud.githubusercontent.com/assets/467411/18038743/6ac84008-6d61-11e6-8aa6-30a776b59aaa.png)

**Comment by fideloper** [comment]
![github-button](https://cloud.githubusercontent.com/assets/467411/18333387/1de356d0-7534-11e6-914d-48d69066cc0d.png)

**Comment by fideloper** [comment]
![github-button_textbox](https://cloud.githubusercontent.com/assets/467411/18333423/8ef22c66-7534-11e6-950d-850be40d9af0.png)

**Comment by aaemnnosttv** [comment]
Wow, great idea 👍
