### ISSUE TITLE
MySQL can't start

### ISSUE THREAD

**Issue by od3n** [shipping-docker/php-app#11]
```
Initializing database
2016-09-26T02:15:55.111480Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2016-09-26T02:15:55.116065Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2016-09-26T02:15:55.116614Z 0 [ERROR] Aborting
2016-09-26T02:15:55.117090007Z 
```

**Comment by fideloper** [comment]
"--initialize specified but the data directory has files in it. " is the
real error but I'll need more information on if you customized anything to
know why that happened.

Basic guess is that the data volume you're (re?)using has files in it
that's not related to MySQL.

**Comment by od3n** [comment]
I just run `docker-compose up -d` for the first time. All other containers are working except db.

![screen shot 2016-09-26 at 11 13 53](https://cloud.githubusercontent.com/assets/156899/18821617/6f73b5da-83da-11e6-984a-8eab1acfe54d.png)

**Comment by fideloper** [comment]
So far I can't recreate it.

Try this:

```bash
# Find your created volumes. 
# There sould be one called phpapp_data
$ docker volume ls

DRIVER              VOLUME NAME
local               phpapp_data

$ docker volume inspect phpapp_data

[
    {
        "Name": "phpapp_data",
        "Driver": "local",
        "Mountpoint": "/var/lib/docker/volumes/phpapp_data/_data",
        "Labels": null,
        "Scope": "local"
    }
]
```

Since Docker on Mac still runs inside of a bit of virtualization, the directory `/var/lib/docker/volumes/phpapp_data/_data` doesn't actually exist on our Mac. But, we can use some docker trickery to see the contents of this directory:

```bash
$ docker run --rm -it -v /:/vm-root alpine:latest ls -l /vm-root/var/lib/docker/volumes/phpapp_data/_data

total 188448
-rw-r-----    1 999      ping            56 Sep 26 12:24 auto.cnf
drwxr-x---    2 999      ping          4096 Sep 26 12:24 homestead
-rw-r-----    1 999      ping          1329 Sep 26 12:24 ib_buffer_pool
-rw-r-----    1 999      ping      50331648 Sep 26 12:24 ib_logfile0
-rw-r-----    1 999      ping      50331648 Sep 26 12:24 ib_logfile1
-rw-r-----    1 999      ping      79691776 Sep 26 12:24 ibdata1
-rw-r-----    1 999      ping      12582912 Sep 26 12:24 ibtmp1
drwxr-x---    2 999      ping          4096 Sep 26 12:24 mysql
drwxr-x---    2 999      ping          4096 Sep 26 12:24 performance_schema
drwxr-x---    2 999      ping         12288 Sep 26 12:24 sys
```


In my case, I can see my MySQL data files just fine. I'm curious to see what you see in that directory. I suspect you have a pre-existing volume named `data` that could be interfering here (although I would be surprised, since it's technically named `phpapp_data`).

**Comment by od3n** [comment]
Never mind, I think I manage to get it resolved.  Probably there are some issue during installation.

I ran these commands to stop & clear all containers :

```
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)

```

List and delete all the volumes :

```
docker volume ls
docker volume rm phpapp_data
```

re-run :

```
docker-compose up -d
```

thank you so much for your help.

btw, how do you connect to mysql using Sequal Pro?

**Comment by fideloper** [comment]
> btw, how do you connect to mysql using Sequal Pro?

In this case, you'll likely need to do a few things:

1. `3306:3306` - Share a port on your mac with port 3306 inside the database container
2. User access - MySQL user access requires specifying the user/password and host from which is allowed to connect. You may need to add a user like `root@%` where `%` is a wildcard saying "user root can connect from any host". That potentially can be done by "logging into" the running DB container and adding a usermanually

```bash
docker exec -it <container_id> bash

> mysql -u root -p
>> create user root@'%' identified by 'some-password';
>> grant all privileges on *.* to root@'%';
```
