### ISSUE TITLE
Multiple sites

### ISSUE THREAD

**Issue by lukasoppermann** [shipping-docker/php-app#12]
Hey @fideloper,

can you maybe let me know how I can use this with multiple websites?

**My setup is:**

> - official nginx + jwilder/docker-gen as a proxy
> - app1: shippingdocker/nginx
>   -   - environment: VIRTUAL_HOST=app1.dev
> - app2: shippingdocker/nginx
>   - environment: VIRTUAL_HOST=app2.dev
> - php: shippingdocker/php

The links are generated fine, however, the php part does not work. So I get a 404 for app2 or a 503.

As per your video it used to be bound to app1:

```
        volumes:
            - ../app1:/var/www/html
```

This does work fine for app1 but of course produces a `404` for app2 as its folder is not bound.
Adding both volumes does not work, I guess you can not bind to /var/www/html twice, which makes sense.

I tried the following on the php container:

```
        volumes:
            - ../apps/app1:/var/www/html/app1
            - ../apps/app2:/var/www/html/app2
```

and on the webservers

```
        volumes:
            - ../app1:/var/www/html/app1
```

But this of course does not work either because the nginx looks for the files in `/var/www/html` (correct?).

Can you maybe advise me what to do? That would be awesome. Thanks.

**Comment by lukasoppermann** [comment]
Nevermind, I just added a php container per app and changed the default file for the different nginx app servers.

**Comment by digitalit** [comment]
Kind of interesting for me as well, 

i now run 2 containers, 1 container with php and nginx and 1 container with db then i have vhosts and multiple databases for all my dev projects and this isn't the Docker way since it is also can be run on production server and should be isolated right?

So basically i guess ill have to have 4 containers per project and i can only run/develop on one project at a time right?

Not an big issue as the up/down i fast but sometimes i need to have 2 project up and running side by side while coding but this isn't possible right?

**Comment by fideloper** [comment]
Thats totally possible - in that case the only limitation is that you can't
share the hosts (e.g. Your mac or Windows) port 80, so for the nginx
container, change the ports option to "8080:80" or "8181:80" per site.

As to whether or not something is the docker way (e.g. "should use the same
containers") that's something to strive for but certainly don't let it get
in the way if getting things done :D

Ive setup containers to get up and running in dev and then have separately
set up some for production later when needed - you can always go back and
change what you use in dev after you have some setup.

I'll cover some strategies on that in the video course!

**Comment by fideloper** [comment]
(To clarify, you just can't have 2 things listening on the same port, so
each site can bind a different port : 80:80 vs 8080:80 vs 8181:80, or
whatever you want).

**Comment by digitalit** [comment]
Thank you for your answer Chris,
I now use: https://github.com/shincoder/homestead-docker but i feel it is just an Dockerized Homestead.

Maybe that is the best for me but i really would like to learn to use Docker and configure my own dev env as flexible as possible.

As for production server i use Forge/Envoyer/DigitalOcean and so far no docker support. Well DigitalOcean supports Docker but i kind of like the whole Laravel env. so for now i will just use Docker in dev.

Got the port thing and i understand. I think Laravel will work fine using ports as "site selector".

I use PhpStorm and i successfully added xdebug to the php image but PS needs ssh to connect so i guess i'll have to install a few more things.

How do i buy a subscription for the Docker video courses?

**Comment by fideloper** [comment]
Right on - definitely use whatever works best for you.

The video series will be a one-time purchase instead of subscription,
probably out November / December!
