### ISSUE TITLE
Mention build option

### ISSUE THREAD

**Issue by lukasoppermann** [shipping-docker/php-app#14]
Hey @fideloper,

I think it would be helpful to talk about the `build` property in the `docker-compose.yml` as well. It is very handy for testing stuff out and I think it is useful if you need to just change the `default` file on an nginx container.

**Comment by fideloper** [comment]
For sure - That was actually my first found of this before it was released: b13c7dbae226e581e23798bece07fb7d68911038

I decided to take it out because it took longer and made docker-compose seem more scarier to new comers.

That'll be covered in the real video series.
