### ISSUE TITLE
can you create a new branch with php 5.6

### ISSUE THREAD

**Issue by manshoor** [shipping-docker/php-app#16]
Hey, so maybe you can create a new branch with php 5.6 with multi site demo?

**Comment by fideloper** [comment]
I'm just teaching a very specific thing here related to the Shipping Docker video series - I unfortunately don't have time to manage it as a full project in that way.

If you [check out the video explanation](https://shippingdocker.com/docker-in-development/) that goes along with this, you can likely figure that out. The key will be to build a php container that installs `php5.6-*` versions of php packages.

**Comment by manshoor** [comment]
Thanks 👍
