### ISSUE TITLE
Response::download()

### ISSUE THREAD

**Issue by iben12** [shipping-docker/php-app#17]
Hi Chris,

I'm having trouble with file download responses with this setup.

It is described in details [here](https://laracasts.com/discuss/channels/laravel/large-file-download-with-nginx-php-fpm), but in short, this:

```php
public function download()
{
    $file = public_path() . '/test.zip';
    $response = Response::download($file);
    return $response;
}
```
results in an ERR_INVALID_RESPONSE in the browser.

The above snippet works as expected if I use the built in server `php -S ...`

**Comment by iben12** [comment]
I have to clarify this after discovering this affects (only?) Laravel 4.2 as the `Response` syntax suggests.

I tried this on Laravel 5.3., with the new `response()->download($file);` and it just works.

**Comment by fideloper** [comment]
Sounds like Laravel 4.2 might not be sending the right headers - likely
need to set some headers in that response before sending the file. For a
.zip file the content headers are probably somewhat generic.
