### ISSUE TITLE
xdebug on php-fpm

### ISSUE THREAD

**Issue by sohelamin** [shipping-docker/php-app#18]
Hi @fideloper 

You did really a great boilerplate of docker and the screencast (y)
I'm using this for my development and I've changed it slightly for my use cases https://github.com/sohelamin/my-docker

But I could not configure the xdebug on it.
Even I've followed this.
https://laracasts.com/discuss/channels/servers/debugging-dont-work-anymore-with-homestead-php7-and-phpstrom

Please could you suggest me how to resolve it or xdebug support into this repo will be much appreciated.

Thanks

**Comment by fideloper** [comment]
Hi! I haven't tried to get xDebg to work within a container yet, but that's
something I should tackle. I think I'd have to install xdebug into the
container (of course), configure it, and then likely expose the port as
part of the docker setup, so things like phpstorm can listen on that port
from the container.

**Comment by sohelamin** [comment]
Thanks @fideloper for getting back to me.
I've tried to install xdebug into a container but failed :(

**Comment by fideloper** [comment]
How far did you get? Interested to see, might tackle that soon!

**Comment by sohelamin** [comment]
Okay I'll try again after deleting all my built images and will let you know soon.

**Comment by sohelamin** [comment]
I've solved it on https://github.com/sohelamin/my-docker/blob/master/docker/app.docker
There was issue with adding php.ini and xdebug config.

You can also add the xdebug support into your boilerplate.

Thanks for helping :)

**Comment by fideloper** [comment]
Awesome, thanks!
