### ISSUE TITLE
Driver failed programming external connectivity

### ISSUE THREAD

**Issue by MonteKrysto** [shipping-docker/php-app#20]
Hi Chris,

Thank you for putting this together.  Is this course already published?  I am looking forward to it.

In following your "Up & Running Quickstart" I have run into this issue, it seems everything is pulled down correctly but when it comes to Nginx I get this:

```
ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint phpapp_nginx_1 (a987d1f81f8395476557fd705c63471fa01346549980c984c0ee8d4ff79dd618): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)
ERROR: Encountered errors while bringing up the project.
```

Any ideas what this may be?

Thanks Chris.

**Comment by fideloper** [comment]
Yep! You have something bound to port 80 on your machine already - possibly a virtual machine (Homestead?) or something like Laravel Valet. (or really anything, maybe you installed Nginx on your computer using brew?)

**Comment by MonteKrysto** [comment]
Thanks Chris.  Yes, I had caddy running on port 80, once I killed it everything ran fine.

**Comment by CasanovaGregory** [comment]
Had the same issue, I killed MAMP and everything goes well. Maybe the error message should by a little bit more obvious for users. Here is what I got : 

ERROR: for frontrouter  Cannot start service frontrouter: driver failed programming external connectivity on endpoint frontrouter (cc42d8dfa5c5c846444131e528b9766a903812ef33818a4554e4e187cd006ed7): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)
ERROR: Encountered errors while bringing up the project.

**Comment by NicholasDsouza1996** [comment]
When i type make run:

Output: ERROR: for postgis Cannot start service postgis: driver failed programming external connectivity on endpoint cartoview_postgis_1 (43f31d100d72e73bdaf7a56887cec57d35838539fc93f0fe77e87b5cf3b1d0f5): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use

**Comment by shippingdocker** [comment]
@CasanovaGregory I can't really control the output of that error message, but I do agree on it being confusing. That being said, the EADDRINUSE error is excruciatingly common, be prepared to run into it a lot in your career!

@NicholasDsouza1996 please don't carpet bomb the repo with the same issue in multiple places.

I answered this in the issue you opened. I need to also mention that your issue isn't related to this repository.

**Comment by bestreaction** [comment]
You can try to "Reset => Restart Docker", if you do not use Valet or Homestead.
