### ISSUE TITLE
module-2/docker-volumes: The path / is reserved by Docker

### ISSUE THREAD

**Issue by vitr** [shipping-docker/php-app#22]
this hack doesn't work with native docker for mac **v 1.13.1**
```
docker run --rm -it -v /:/vm-root \
    alpine:latest ls -lah /vm-root/var/lib/docker/volumes/volume_name_or_generated_hash/_data
```

**Comment by fideloper** [comment]
Hi!

That seemed to work here for me - do you have any different settings?

![image](https://cloud.githubusercontent.com/assets/467411/23093791/1c689168-f5b2-11e6-8999-a89861166149.png)

![image](https://cloud.githubusercontent.com/assets/467411/23093795/3038f05c-f5b2-11e6-9cc2-37d5132aad96.png)

**Comment by vitr** [comment]
yeah, sorry, couldn't add the root / in docker and gave up before actually running it
![image](https://cloud.githubusercontent.com/assets/2770290/23093870/e22cb758-f639-11e6-9e73-448402101fb7.png)
