### ISSUE TITLE
MySQL Timeout Issue

### ISSUE THREAD

**Issue by stevepop** [shipping-docker/php-app#25]
I was following the course until I got to the `Serving a Real Application` lesson and tried to run the Laravel's artisan migrate command. I got the following timeout error
```
sandbox/dcker »  docker run -it --rm \
    -v $(pwd)/application:/opt \
    -w /opt \
    --network=st-net \
    stevepop/php:0.1.0 \
    php artisan migrate

  [Illuminate\Database\QueryException]
  SQLSTATE[HY000] [2002] Connection timed out (SQL: select * from information_schema.tables where table_schema = my-app and table_name = migrations)

  [PDOException]
  SQLSTATE[HY000] [2002] Connection timed out
```
I really don't understand what the problem is as all the containers belong to the same network and one would expect they can talk to each other.

**Comment by fideloper** [comment]
Hi! I'll not sure either, could be a mismatch with network names or could
be that the MySQL server was still booting up (it can take a bit if time
thr first run).

Assuming you're using docker compose as well at this point, you can also
try:

docker-compose run --rm -w /var/www/html app php artisan migrate

That will use docker compose settings for volume mounting, network, and
container definition. (Yoy may need to change the working directory if
you're using diff file paths).

**Comment by stevepop** [comment]
Hi @fideloper, thanks for your response. This is what worked,
`docker-compose run --rm -w /var/www/html php php artisan migrate`.
Posting my response in case someone else experience the same issue.

**Comment by mludi** [comment]
Close this issue please.
