### ISSUE TITLE
Cartoview installation using docker issue

### ISSUE THREAD

**Issue by NicholasDsouza1996** [shipping-docker/php-app#28]
When i type make run:

Output: ERROR: for postgis  Cannot start service postgis: driver failed programming external connectivity on endpoint cartoview_postgis_1 (43f31d100d72e73bdaf7a56887cec57d35838539fc93f0fe77e87b5cf3b1d0f5): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use

**Comment by fideloper** [comment]
bind: address already in use is the error to pay attention to there.


The port 5432 is likely already in use from another container somewhere.

On Fri, Sep 1, 2017 at 8:50 AM, NicholasDsouza1996 <notifications@github.com
