### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by seandelaney** [shipping-docker/php-app#30]
Once I've run the composer command to install Laravel, I get a `403 Forbidden` error when trying to view http://localhost again.

However, in the previous step, before we installed Laravel and we just had a simple index.php file in `/application` with `<?php phpinfo()` as the contents, everything worked fine.

The problem has come after installing Laravel.

Are there specific permissions I need to run?

```
docker run -it --rm -v $(pwd):/opt -w /opt --network=app-net shipping-docker/php:0.2.0 composer create-project laravel/laravel application
```

```
docker run -it --rm -v $(pwd)/application:/opt -w /opt --network=app-net  shipping-docker/php:0.2.0 composer require predis/predis
```

My docker-compose.yml file has not changed and is still the same as per the shipping docker video tutorials:

```
        volumes:
            - ./application:/var/www/html
```

If I look in `/application`, I can see all the Laravel files and folder, which I've not touched.

If I check the logs by running `docker logs dckr_nginx_1` I see:

```
2017/11/08 13:24:56 [error] 5#5: *3 directory index of "/var/www/html/" is forbidden, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
172.18.0.1 - - [08/Nov/2017:13:24:56 +0000] "GET / HTTP/1.1" 403 580 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"
```

Not exactly sure what is wrong?

I'm running Docker for Mac, Version 17.09.0-ce-mac35 (19611) Channel: stable a98b7c1b7c.

**Comment by fideloper** [comment]
The web root set by Nginx is /var/www/html/public (laravel should have a
`public` directory). Can you confirm that path has your code?

Run: `docker-compose exec app ls -lah /var/www/html/public`

That will list out the directory /var/www/html/public in your container.
You can also shorten the path to /var/www/html to confirm there are files
at that location.

Are you running Docker on Mac? (Or on linux?)

**Comment by seandelaney** [comment]
> The web root set by Nginx is /var/www/html/public (laravel should have a
> `public` directory). Can you confirm that path has your code?

Yes, I see a `public` folder instead `/application`


> Run: `docker-compose exec app ls -lah /var/www/html/public`

seandelaney@SeanDelaneysMBP ~/Sites/docker (master) $ docker-compose exec nginx ls -lah /var/www/html/public
total 16K
drwxr-xr-x  9 www-data www-data  306 Aug 30 09:55 .
drwxr-xr-x 24 www-data www-data  816 Nov  8 12:59 ..
-rw-r--r--  1 www-data www-data  584 Aug 30 09:55 .htaccess
drwxr-xr-x  3 www-data www-data  102 Aug 30 09:55 css
-rw-r--r--  1 www-data www-data    0 Aug 30 09:55 favicon.ico
-rw-r--r--  1 www-data www-data 1.8K Aug 30 09:55 index.php
drwxr-xr-x  3 www-data www-data  102 Aug 30 09:55 js
-rw-r--r--  1 www-data www-data   24 Aug 30 09:55 robots.txt
-rw-r--r--  1 www-data www-data  914 Aug 30 09:55 web.config


> Are you running Docker on Mac? (Or on linux?)

I'm running Docker for Mac, Version 17.09.0-ce-mac35 (19611) Channel: stable a98b7c1b7c.

**Comment by seandelaney** [comment]
> The web root set by Nginx is /var/www/html/public 

I'm a bit confused by this comment though.

Following your video tutorial, building the NGINX image based on Ubuntu, the root was `/var/www/html`

Then in the docker-compose, the volume was also set to:

```
volumes:
            - ./application:/var/www/html
```

Should I have:

```
volumes:
            - ./application:/var/www/html/public

```
?

**Comment by seandelaney** [comment]
Okay, so I see the problem.

In the shipping-docker video tutorials, when we build the NGINX image, the root is set to `/var/www/html` by default.

This is all fine until we get to your "Serving Real Applications" lesson for the Shipping Docker course. We hit a roadblock. You don't mention that we need to update the NGNIX root to `var/www/html/public` in `default` as per https://github.com/shipping-docker/php-app/blob/master/build/nginx/default

**Comment by seandelaney** [comment]
I rebuild my NGINX image with the root now set to `/var/www/html/public` and everything is working fine. I can see the Laravel landing page.

Thank you!
