### ISSUE TITLE
Cannot run PHP artisan commands

### ISSUE THREAD

**Issue by seandelaney** [shipping-docker/php-app#32]
@fideloper

I'm following the paid subscription video tutorials and I'm currently installing Laravel on the remote Docker container.

When I try running:

```
docker run -it --rm -v /srv/application:/opt -w /opt --network=some_network shippingdocker/php php artisan make:auth
```

I get:

```
PHP Warning:  require(/opt/vendor/autoload.php): failed to open stream: No such file or directory in /opt/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/opt/vendor/autoload.php' (include_path='.:/usr/share/php') in /opt/artisan on line 18
```

I can run 

```docker run -it --rm -v /srv/application:/opt -w /opt --network=some_network shippingdocker/php php -v``` without any issue and I get back the PHP version.

If I SSH into the container and navigate to the `/srv/application` directory, I can see all the Laravel files listed, including an `artisan` file.

Please advise.

**Comment by seandelaney** [comment]
I think I might have found the issue but not sure how to fix it.

After you install Laravel and run composer to install Predis, there is still no `vendor` folder.

I don't understand. Composer commands run without any issues and tells me everything was installed/updated.

**Comment by seandelaney** [comment]
So I've managed to figure out what the issue was!

TBH, I think I had a stroke of luck as when I previously ran the same commands from the video tutorials, I wasn't getting back any errors so I had no idea why the vendor folder was not created or why the composer packages were not installing...

So I killed my Digital Ocean droplet thinking something was wrong with permissions etc...

Created a new droplet, fired up all the containers using the `docker-compose.yml` file and then this time when I ran the `docker run ...` command I got this:

```
seandelaney@Sean-Delaneys-MacBook-Pro ~/Sites/shipping-docker/module-7 $ docker run -it --rm -v /srv/application:/opt -w /opt --network=appnet shippingdocker/php composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/thanks (v1.0.1)
    Downloading: 100%
The following exception is caused by a lack of memory or swap, or not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details

PHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///usr/bin/composer/vendor/symfony/console/Application.php on line 957

Warning: proc_open(): fork failed - Cannot allocate memory in phar:///usr/bin/composer/vendor/symfony/console/Application.php on line 957

  [ErrorException]
  proc_open(): fork failed - Cannot allocate memory


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]... 
```

Bingo. Finally some insight into the issue. Lack of memory. So I sorted the memory issue and re-ran the commands again and Composer has now installed all the packages correctly.

Which now gives me a `/vendor` folder with `/vendor/autoload.php` that allows Artisan commands to run!

**Comment by Tai7sy** [comment]
可以运行一下相关的命令试一下, 如果还是没有输出, 请检查你的php环境和程序源码是否完整
```
ubuntu@Windy:/mnt/d/MyProjects/card/card$ php --version
PHP 7.2.10 (cli) (built: Oct 20 2018 18:54:13) ( NTS )

ubuntu@Windy:/mnt/d/MyProjects/card/card$ php artisan
Laravel Framework 5.5.44

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --env[=ENV]       The environment the command should run under
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```
