### ISSUE TITLE
Error when running composer create-project

### ISSUE THREAD

**Issue by Veuge** [shipping-docker/php-app#35]
When I try to run

```
docker run -it --rm \
    -v $(pwd):/opt \
    -w /opt \
    --network=phpapp_appnet \
    shippingdocker/php \
    composer create-project laravel/laravel application
```

I get the error:

`[Composer\Downloader\TransportException]
The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution`

**Comment by fideloper** [comment]
`Temporary failure in name resolution` says it all, I think!

In this case, the error is coming from Composer I believe - perhaps a hiccup in composer's service. 

Either that or something in your Docker setup is preventing it from reaching the external internet (assuming you haven't done any other custom configurations to your docker setup, I'd try restarting Docker itself).

**Comment by Veuge** [comment]
I kind of figured out that there seems to be something wrong with the network configuration. So changing `--network=phpapp_appnet` by `--network=host` solves the issue

**Comment by Pushkar-Rana** [comment]
First, thanks for the docker video course. 
I am also facing the same issue in both Windows & Linux system. I have attached the docker composer file along with build files.

Please help me, how to resolve this issue.

[project.zip](https://github.com/shipping-docker/php-app/files/1898121/project.zip)
