### ISSUE TITLE
Error when running composer create-project with docker-compose

### ISSUE THREAD

**Issue by Pushkar-Rana** [shipping-docker/php-app#36]
First, thanks for the docker video course. 

When I try to run composer to create the project, I get this error in both Windows & Linux system.

`[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution`

Command to run composer 
`docker run -it --rm -v $(pwd):/opt -w /opt --network=project_code-net rana/php:7.0 composer create-project laravel/laravel application`

I have attached the docker composer file along with build files.

Please help me, how to resolve this issue.

[project.zip](https://github.com/shipping-docker/php-app/files/1898121/project.zip)

**Comment by fideloper** [comment]
So far as I can tell, that just means your internet couldn't reach packagist.org (likely a temporary issue). "Name resolution" means changing the domain packagist.org into a IP address via DNS.

**Comment by Pushkar-Rana** [comment]
Yes, this issue was related to Docker's DNS setting. After adding code in "/etc/docker/daemon.json" file, resolved this issue.

```
{
    "dns": ["10.0.0.2", "8.8.8.8"]
}
```
This is the reference link "https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/" for more information.

**Comment by Geowan** [comment]
Also for those using docker compose dont you can also add     
dns:
    - 8.8.8.8
    - 4.4.4.4
    - 0.0.0.0
on the services like

     services:
       app:
        dns:
        - 8.8.8.8
        - 4.4.4.4
         - 0.0.0.0
