### ISSUE TITLE
nginx fpm conf

### ISSUE THREAD

**Issue by aaemnnosttv** [shipping-docker/php-app#5]
This is more of a question than a problem, if there's a better place for this kind of thing just let me know.

My understanding of php-fpm is that it is more performant for nginx to use a unix socket for fpm rather than using the tcp port 9000 as there is less overhead.  Does multi-container architecture make the unix socket more problematic to share/scale than using the port?  Just curious if this is required or just easier to implement than leveraging the docker network.  

Looking forward to the full course!  Thanks!

**Comment by fideloper** [comment]
Hi!

Yep, unix sockets are a little faster (I don't think by much, but haven't benchmarked to find out for myself).

At first, I considered making that setup (sharing a unix socket file between the two containers) work, which could likely be done with a shared volume, just like the mysql container uses.

However I decided to make them separate containers as it gives me the opportunity to show how the networking works within docker-compose and Docker's `network` command. In that case, doing a TCP socket (e.g. ipaddress:port) is what I had to do!

I actually haven't attempted to get a shared unix socket working between two containers before (although it sounds totally doable with shared volumes), but I **have** put Nginx and FPM within the same container before, which I find to be an overall good pairing (that lets you use the unix socket easily as well).
